### ISSUE TITLE
Helm Release Resource Name should be aws-load-balancer-controller

### ISSUE THREAD

**Issue by torgus** [lablabs/terraform-aws-eks-load-balancer-controller#4]
Just for cosmetic reasons, name of the terraform helm release resource should be named as the module name: aws-load-balancer-controller

https://github.com/lablabs/terraform-aws-eks-load-balancer-controller/blob/8303efa381dbedeb0af045ff2a3ac85d01fae69f/main.tf#L24

**Comment by torgus** [comment]
https://github.com/lablabs/terraform-aws-eks-load-balancer-controller/pull/5

**Comment by Thumbiceq** [comment]
Hello @torgus,

thank you for reporting this. There is already new [PR #7 ](https://github.com/lablabs/terraform-aws-eks-load-balancer-controller/pull/7) where this issue is handled along with new module structure.

**Comment by dojci** [comment]
Please see the [new release](https://github.com/lablabs/terraform-aws-eks-load-balancer-controller/releases/tag/v1.0.0).
