### ISSUE TITLE
deprecated wait_for option on latest terraform verions

### ISSUE THREAD

**Issue by flowinh2o** [lablabs/terraform-aws-eks-load-balancer-controller#8]
The "wait_for" attribute has been deprecated. Please use the "wait" block │ instead. Seeing this warning with terraform version 1.1.7

https://github.com/lablabs/terraform-aws-eks-load-balancer-controller/blob/27678c42a4033c7c043fb844f01eb146159fec80/argo.tf#L82

**Comment by tomas-balaz** [comment]
Fixed in #10
